--[[
https://docs.fivem.net/natives/?_0x2BDD44CC428A7EAE
0 = american (en-US)
1 = french (fr-FR)
2 = german (de-DE)
3 = italian (it-IT)
4 = spanish (es-ES)
5 = brazilian (pt-BR) ADICIONADA
6 = polish (pl-PL)
7 = russian (ru-RU)
8 = korean (ko-KR)
9 = chinesetrad (zh-t)
10 = japanese (ja-JP)
11 = mexican (es-MX)
12 = chinesesimp (zh-s)
]]

local languageCode = {
	[0]="en",
	[1]="fr",
	[2]="de",
	[3]="it",
	[4]="es",
	[5]="br",
	[6]="pl",
	[7]="ru",
	[8]="ko",
	[9]="zh",
	[10]="jp",
	[11]="mx",
	[12]="cn"
}

local translation = {
	-- MainMenu
	["MainMenu-Title"] = {
		["en"] = "Race Creator",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Criador de Corridas",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "竞速制作器"
	},
	["MainMenu-Subtitle"] = {
		["en"] = "Items",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Itens",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "选项"
	},
	["MainMenu-Button-Create"] = {
		["en"] = "Create New Race",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Criar Nova Corrida",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "创建新的比赛"
	},
	["MainMenu-Button-Import"] = {
		["en"] = "Import From Rockstar UGC",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Importar do Rockstar UGC",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "从Rockstar UGC导入"
	},
	["MainMenu-Button-Cancel"] = {
		["en"] = "Cancel Querying",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Cancelar Consulta",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "取消查询"
	},
	["MainMenu-Separator-Load"] = {
		["en"] = "Load Race",
		["br"] = "Carregar Corrida",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "加载比赛"
	},
	["MainMenu-Button-RaceDetail"] = {
		["en"] = "Race Detail",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Detalhes da Corrida",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "比赛详情"
	},
	["MainMenu-Button-Placement"] = {
		["en"] = "Placement",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Posicionamento",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "放置项目"
	},
	["MainMenu-Button-Multiplayer"] = {
		["en"] = "Multiplayer",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Multijogador",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "多人创作"
	},
	["MainMenu-Button-Weather"] = {
		["en"] = "Weather Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Clima",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "天气设置"
	},
	["MainMenu-Button-Time"] = {
		["en"] = "Time Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Horário",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "时间设置"
	},
	["MainMenu-Button-Save"] = {
		["en"] = "Save Map",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Salvar Mapa",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "保存地图"
	},
	["MainMenu-Button-Update"] = {
		["en"] = "Update Map",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Atualizar Mapa",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "更新地图"
	},
	["MainMenu-Button-Publish"] = {
		["en"] = "Publish Map",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Publicar Mapa",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "发布地图"
	},
	["MainMenu-Button-CancelPublish"] = {
		["en"] = "Cancel Publish",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Cancelar Publicação",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "取消发布"
	},
	["MainMenu-Button-Export"] = {
		["en"] = "Export Map",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Exportar Mapa",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "导出地图"
	},
	["MainMenu-Button-Save-Desc"] = {
		["en"] = "Title already exists / Invalid thumbnail / StartingGrid 0 / Checkpoints less than 10 / Props 0",
		["br"] = "Título já existe / Miniatura inválida / Grade de início 0 / Menos de 10 pontos de controle / Props 0",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "标题已存在/缩略图无效/起跑点数量0/检查点数量小于10/道具数量0"
	},
	["MainMenu-Button-CancelPublish-Desc"] = {
		["en"] = "This will unpublish the race, but the file will still exist",
		["br"] = "Isso irá despublicar a corrida, mas o arquivo ainda existirá",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "这将把这个比赛取消发布，但是文件仍然存在"
	},
	["MainMenu-Button-Misc"] = {
		["en"] = "Misc Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções Diversos",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "杂项设置"
	},
	["filter-races"] = {
		["en"] = "Filter Results",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Filtrar Resultados",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "筛选结果"
	},
	["published-races"] = {
		["en"] = "Published Races",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Corridas Publicadas",
		["mx"] = "",
		["cn"] = "已发布的竞速"
	},
	["saved-races"] = {
		["en"] = "Saved Races",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Corridas Salvas",
		["mx"] = "",
		["cn"] = "已保存的竞速"
	},
	["MainMenu-Button-Exit"] = {
		["en"] = "Exit Menu",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Fechar Menu",
		["mx"] = "",
		["cn"] = "退出菜单"
	},
	["MainMenu-Button-Filter"] = {
		["en"] = "Filter Races",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Filtro de Corridas",
		["mx"] = "",
		["cn"] = "筛选比赛"
	},

	-- RaceDetailSubMenu
	["RaceDetailSubMenu-Subtitle"] = {
		["en"] = "Race Detail",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Detalhes da Corrida",
		["mx"] = "",
		["cn"] = "比赛详情"
	},
	["RaceDetailSubMenu-Button-Title"] = {
		["en"] = "Title",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Título da Corrida",
		["mx"] = "",
		["cn"] = "标题"
	},
	["RaceDetailSubMenu-Button-Title-Desc"] = {
		["en"] = "Title already exists",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Título",
		["mx"] = "",
		["cn"] = "标题已存在"
	},
	["RaceDetailSubMenu-Button-Thumbnail"] = {
		["en"] = "Thumbnail",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Miniatura",
		["mx"] = "",
		["cn"] = "缩略图"
	},
	["RaceDetailSubMenu-Button-Thumbnail-Desc"] = {
		["en"] = "Invalid thumbnail",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Miniatura inválida",
		["mx"] = "",
		["cn"] = "缩略图无效"
	},
	["RaceDetailSubMenu-Button-TestVeh"] = {
		["en"] = "Default Test Vehicle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Veículo de Teste Padrão",
		["mx"] = "",
		["cn"] = "默认测试载具"
	},
	["RaceDetailSubMenu-Button-Blimp"] = {
		["en"] = "Blimp Text",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Texto do Dirigível",
		["mx"] = "",
		["cn"] = "飞艇文本"
	},

	-- PlacementSubMenu
	["PlacementSubMenu-Subtitle"] = {
		["en"] = "Placement",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Posicionamento",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "放置项目"
	},
	["PlacementSubMenu-Button-StartingGrid"] = {
		["en"] = "Starting Grid",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Grade de Início",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "起跑位"
	},
	["PlacementSubMenu-Button-StartingGrid-Desc"] = {
		["en"] = "StartingGrid 0",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Grade de Início 0",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "起跑点数量0"
	},
	["PlacementSubMenu-Button-Checkpoints"] = {
		["en"] = "Checkpoints",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Pontos de Controle",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "检查点"
	},
	["PlacementSubMenu-Button-Checkpoints-Desc"] = {
		["en"] = "Checkpoints less than 10",
		["br"] = "Menos de 10 pontos de controle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "检查点数量小于10"
	},
	["PlacementSubMenu-Button-Props"] = {
		["en"] = "Props",
		["br"] = "Props",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "道具"
	},
	["PlacementSubMenu-Button-Props-Desc"] = {
		["en"] = "Props 0",
		["br"] = "Props 0",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "道具数量0"
	},
	["PlacementSubMenu-Button-Templates"] = {
		["en"] = "Templates",
		["br"] = "Modelos",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "模板"
	},
	["PlacementSubMenu-Button-Templates-Desc"] = {
		["en"] = "Templates 0",
		["br"] = "Modelos 0",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "模板数量0"
	},
	["PlacementSubMenu-Button-MoveAll"] = {
		["en"] = "Move All",
		["br"] = "Mover Todos",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "移动全部"
	},
	["PlacementSubMenu-Button-MoveAll-Desc"] = {
		["en"] = "Move All 0",
		["br"] = "Mover Todos 0",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "移动全部0"
	},
	["PlacementSubMenu-Button-FixtureRemover"] = {
		["en"] = "Fixture Remover",
		["br"] = "Removedor de Fixações",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "固定装置移除"
	},
	["PlacementSubMenu-Button-FixtureRemover-Desc"] = {
		["en"] = "FixtureRemover 0",
		["br"] = "Removedor de Fixações 0",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "固定装置移除0"
	},
	["PlacementSubMenu-Button-Firework"] = {
		["en"] = "Firework",
		["br"] = "Fogos de Artifício",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "烟花"
	},
	["PlacementSubMenu-Button-Firework-Desc"] = {
		["en"] = "Firework 0",
		["br"] = "Fogos de Artifício 0",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "烟花0"
	},

	-- PlacementSubMenu_StartingGrid
	["PlacementSubMenu_StartingGrid-Subtitle"] = {
		["en"] = "Starting Grid Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Grade de Início",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "起跑位设置"
	},
	["PlacementSubMenu_StartingGrid-Button-Place"] = {
		["en"] = "Place New Starting Grid",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Colocar Nova Grade de Início",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "放置新的起跑位"
	},
	["PlacementSubMenu_StartingGrid-Button-startingGridLimit-Desc"] = {
		["en"] = "Maximum limit reached : " .. Config.StartingGridLimit,
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Limite máximo atingido : " .. Config.StartingGridLimit,
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "已达最大限制 : " .. Config.StartingGridLimit
	},
	["PlacementSubMenu_StartingGrid-List-Heading"] = {
		["en"] = "Heading:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Orientação:",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "朝向:"
	},
	["PlacementSubMenu_StartingGrid-List-ChangeSpeed"] = {
		["en"] = "Change Speed",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Alterar Velocidade",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "调整速度"
	},
	["PlacementSubMenu_StartingGrid-Button-Delete"] = {
		["en"] = "    Delete Starting Grid",
		["br"] = "    Excluir Grade de Início",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "    删除起跑位"
	},
	["PlacementSubMenu_StartingGrid-List-CycleItems"] = {
		["en"] = "Cycle Items",
		["br"] = "Alternar Itens",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "循环项目"
	},

	-- PlacementSubMenu_Checkpoints
	["PlacementSubMenu_Checkpoints-Subtitle"] = {
		["en"] = "Checkpoints Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Pontos de Controle",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "检查点设置"
	},
	["PlacementSubMenu_Checkpoints-Button-Test"] = {
		["en"] = "Test Current Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Testar Ponto de Controle Atual",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "测试当前检查点"
	},
	["PlacementSubMenu_Checkpoints-List-Primary"] = {
		["en"] = "Primary Checkpoints",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Pontos de Controle Principais",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "主要检查点"
	},
	["PlacementSubMenu_Checkpoints-List-Secondary"] = {
		["en"] = "Secondary Checkpoints",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Pontos de Controle Secundários",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "次要检查点"
	},
	["PlacementSubMenu_Checkpoints-Button-Place"] = {
		["en"] = "Place New Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Colocar Novo Ponto de Controle",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "放置新的检查点"
	},
	["PlacementSubMenu_Checkpoints-List-Heading"] = {
		["en"] = "Heading:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Orientação:",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "朝向:"
	},
	["PlacementSubMenu_Checkpoints-List-ChangeSpeed"] = {
		["en"] = "Change Speed",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Alterar Velocidade",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "调整速度"
	},
	["PlacementSubMenu_Checkpoints-List-Diameter"] = {
		["en"] = "Diameter:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Diâmetro:",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "直径:"
	},
	["PlacementSubMenu_Checkpoints-CheckBox-Round"] = {
		["en"] = "Set As Round Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Definir Como Ponto de Controle Circular",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "设置为圆形检查点"
	},
	["PlacementSubMenu_Checkpoints-CheckBox-Air"] = {
		["en"] = "Set As Air Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Definir Como Ponto de Controle de Ar",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "设置为空中检查点"
	},
	["PlacementSubMenu_Checkpoints-CheckBox-Fake"] = {
		["en"] = "Set As Fake Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Definir Como Ponto de Controle Falso",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "设置为假检查点"
	},
	["PlacementSubMenu_Checkpoints-CheckBox-Random"] = {
		["en"] = "Set As Random Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Definir Como Ponto de Controle Aleatório",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "设置为随机幻变检查点"
	},
	["PlacementSubMenu_Checkpoints-List-Random"] = {
		["en"] = "Random Class:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Classe Aleatória:",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "随机类别:"
	},
	["RandomClass-0"] = {
		["en"] = "Land Vehicle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Veículo Terrestre",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "陆地载具"
	},
	["RandomClass-1"] = {
		["en"] = "Air Vehicle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Veículo Aéreo",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "空中载具"
	},
	["RandomClass-2"] = {
		["en"] = "Boat Vehicle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Veículo Aquático",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "水上载具"
	},
	["RandomClass-3"] = {
		["en"] = "Air + Land",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Ar + Terra",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "空中 + 陆地"
	},
	["PlacementSubMenu_Checkpoints-CheckBox-Transform"] = {
		["en"] = "Set As Transform Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Definir Como Ponto de Controle Transformado",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "设置为幻变检查点"
	},
	["PlacementSubMenu_Checkpoints-List-Transform"] = {
		["en"] = "Transform Vehicle:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Veículo Transformado:",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "幻变载具:"
	},
	["Transform-Parachute"] = {
		["en"] = "Parachute",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Paraquedas",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "降落伞"
	},
	["Transform-Beast"] = {
		["en"] = "Beast",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Lobo",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "狼人"
	},
	["Transform-Default"] = {
		["en"] = "Default Vehicle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Veículo Padrão",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "默认车辆"
	},
	["PlacementSubMenu_Checkpoints-Button-Transform"] = {
		["en"] = "Manage Transform Vehicles",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Gerenciar Veículos Transformados",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "管理幻变载具"
	},
	["PlacementSubMenu_Checkpoints-CheckBox-PlaneRot"] = {
		["en"] = "Set As Plane Rot Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Definir Como Ponto de Controle de Rotação do Avião",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "设置为飞行方向检查点"
	},
	["PlacementSubMenu_Checkpoints-List-PlaneRot"] = {
		["en"] = "Pass Rotation",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Rotação",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "通过方向"
	},
	["PlaneRot-0"] = {
		["en"] = "Up",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Acima",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "上"
	},
	["PlaneRot-1"] = {
		["en"] = "Right",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Direita",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "右"
	},
	["PlaneRot-2"] = {
		["en"] = "Down",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Abaixo",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "下"
	},
	["PlaneRot-3"] = {
		["en"] = "Left",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Esquerda",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "左"
	},
	["PlacementSubMenu_Checkpoints-CheckBox-Warp"] = {
		["en"] = "Set As Warp Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Definir Como Ponto de Controle de Torção",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "设置为扭曲检查点"
	},
	["PlacementSubMenu_Checkpoints-Button-Delete"] = {
		["en"] = "    Delete Checkpoint",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "    删除检查点",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "    删除检查点"
	},
	["PlacementSubMenu_Checkpoints-List-CycleItems"] = {
		["en"] = "Cycle Items",
		["br"] = "Alternar Itens",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "循环项目"
	},

	-- PlacementSubMenu_Props
	["PlacementSubMenu_Props-Subtitle"] = {
		["en"] = "Props Options",
		["br"] = "Opções de Props",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "道具设置"
	},
	["PlacementSubMenu_Props-Button-EnterModelHash"] = {
		["en"] = "Enter A Valid Model",
		["br"] = "Digite um Modelo Válido",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "输入一个有效的模型"
	},
	["PlacementSubMenu_Props-Button-EnterModelHash-Desc"] = {
		["en"] = "For more information visit: forge.plebmasters.de/objects",
		["br"] = "Para mais informações acesse: forge.plebmasters.de/objects",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "更多信息访问: forge.plebmasters.de/objects"
	},
	["PlacementSubMenu_Props-List-Category"] = {
		["en"] = "Category (%s/%s):",
		["br"] = "Categoria (%s/%s):",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "类别 (%s/%s):"
	},
	["PlacementSubMenu_Props-List-Model"] = {
		["en"] = "Model (%s/%s):",
		["br"] = "Modelo (%s/%s):",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "模型 (%s/%s):"
	},
	["PlacementSubMenu_Props-Button-Place"] = {
		["en"] = "Place New Prop",
		["br"] = "Colocar Novo Prop",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "放置新的道具"
	},
	["PlacementSubMenu_Props-Button-objectLimit-Desc"] = {
		["en"] = "Maximum limit reached : " .. Config.ObjectLimit,
		["br"] = "Limite máximo atingido : " .. Config.ObjectLimit,
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "已达最大限制 : " .. Config.ObjectLimit
	},
	["PlacementSubMenu_Props-CheckBox-Stack"] = {
		["en"] = "Automatic Stack Prop",
		["br"] = "Empilhar Props Automaticamente",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "自动堆叠道具"
	},
	["PlacementSubMenu_Props-CheckBox-Stack-Desc"] = {
		["en"] = "Aka: prop snapping",
		["br"] = "Também conhecido como: encaixe de props",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "又称: 道具拼接"
	},
	["PlacementSubMenu_Props-List-BoneIndexParent"] = {
		["en"] = "Parent Prop Bone Index:",
		["br"] = "Índice de Osso do Prop Pai:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "父道具节点:"
	},
	["PlacementSubMenu_Props-List-BoneIndexParent-Desc"] = {
		["en"] = "Parent prop has 0 valid bone",
		["br"] = "Prop pai não possui ossos válidos",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "父道具没有有效的骨骼节点"
	},
	["PlacementSubMenu_Props-List-BoneIndexChild"] = {
		["en"] = "Child Prop Bone Index:",
		["br"] = "Índice de Osso do Prop Filho:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "子道具节点:"
	},
	["PlacementSubMenu_Props-List-BoneIndexChild-Desc"] = {
		["en"] = "Child prop has 0 valid bone",
		["br"] = "Prop filho não possui ossos válidos",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "子道具没有有效的骨骼节点"
	},
	["PlacementSubMenu_Props-List-Alignment"] = {
		["en"] = "Alignment",
		["br"] = "Alinhamento",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "对齐方式"
	},
	["PlacementSubMenu_Props-List-Alignment-World"] = {
		["en"] = "World",
		["br"] = "Mundo",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "世界"
	},
	["PlacementSubMenu_Props-List-Alignment-Relative"] = {
		["en"] = "Relative",
		["br"] = "Relativo",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "相对"
	},
	["PlacementSubMenu_Props-List-ChangeSpeed"] = {
		["en"] = "Change Speed",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Alterar Velocidade",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "调整速度"
	},
	["PlacementSubMenu_Props-Button-Override"] = {
		["en"] = "Prop Batch Override",
		["br"] = "Substituição em Lote de Props",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "道具批量修改"
	},
	["PlacementSubMenu_Props-List-Color"] = {
		["en"] = "Color:",
		["br"] = "Cor:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "颜色:"
	},
	["PlacementSubMenu_Props-CheckBox-Visible"] = {
		["en"] = "Visible",
		["br"] = "Visível",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "可见"
	},
	["PlacementSubMenu_Props-CheckBox-Collision"] = {
		["en"] = "Collision",
		["br"] = "Colisão",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "碰撞"
	},
	["PlacementSubMenu_Props-CheckBox-Dynamic"] = {
		["en"] = "Dynamic",
		["br"] = "Dinâmico",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "动态"
	},
	["PlacementSubMenu_Props-Button-Delete"] = {
		["en"] = "    Delete Prop",
		["br"] = "    Excluir Prop",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "    删除道具"
	},
	["PlacementSubMenu_Props-List-CycleItems"] = {
		["en"] = "Cycle Items",
		["br"] = "Alternar Itens",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "循环项目"
	},

	-- PlacementSubMenu_Templates
	["PlacementSubMenu_Templates-Subtitle"] = {
		["en"] = "Templates Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Modelos",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "模板设置"
	},
	["PlacementSubMenu_Templates-List-Templates"] = {
		["en"] = "Templates:",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Modelos:",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "模板:"
	},
	["PlacementSubMenu_Templates-Button-SaveTemplate"] = {
		["en"] = "Save Template",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Salvar Modelo",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "保存模板"
	},
	["PlacementSubMenu_Templates-Button-SaveTemplate-Desc1"] = {
		["en"] = "Maximum limit reached : " .. Config.TemplateLimit,
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Limite máximo atingido : " .. Config.TemplateLimit,
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "已达最大限制 : " .. Config.TemplateLimit
	},
	["PlacementSubMenu_Templates-Button-SaveTemplate-Desc2"] = {
		["en"] = "The first selected prop will reset the Euler angles",
		["br"] = "O primeiro prop selecionado irá redefinir os ângulos de Euler",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "第一个选中的道具会重置欧拉角"
	},
	["PlacementSubMenu_Templates-Button-PlaceTemplate"] = {
		["en"] = "Place Template",
		["br"] = "Colocar Modelo",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "放置模板"
	},
	["PlacementSubMenu_Templates-List-ChangeSpeed"] = {
		["en"] = "Change Speed",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Alterar Velocidade",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "调整速度"
	},
	["PlacementSubMenu_Templates-Button-Override"] = {
		["en"] = "Template Batch Override",
		["br"] = "Substituição em Lote de Modelos",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "模板批量修改"
	},
	["PlacementSubMenu_Templates-Button-Delete"] = {
		["en"] = "    Delete Template",
		["br"] = "    Excluir Template",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "    删除模板"
	},

	-- PlacementSubMenu_MoveAll
	["PlacementSubMenu_MoveAll-Subtitle"] = {
		["en"] = "Move All",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Mover Todos",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "移动全部"
	},
	["PlacementSubMenu_MoveAll-List-ChangeSpeed"] = {
		["en"] = "Change Speed",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Alterar Velocidade",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "调整速度"
	},

	-- PlacementSubMenu_FixtureRemover
	["PlacementSubMenu_FixtureRemover-Subtitle"] = {
		["en"] = "Fixture Remover Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Remover Fixação",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "固定装置移除设置"
	},
	["PlacementSubMenu_FixtureRemover-Button-Select"] = {
		["en"] = "Select Fixture",
		["br"] = "Selecionar Fixação",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "选择固定装置"
	},
	["PlacementSubMenu_FixtureRemover-Button-Deselect"] = {
		["en"] = "    Deselect Fixture",
		["br"] = "    Desmarcar Fixação",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "    取消选择固定装置"
	},
	["PlacementSubMenu_FixtureRemover-List-CycleItems"] = {
		["en"] = "Cycle Items",
		["br"] = "Alternar Itens",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "循环项目"
	},

	-- PlacementSubMenu_Firework
	["PlacementSubMenu_Firework-Subtitle"] = {
		["en"] = "Firework Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Fogos de Artifício",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "烟花设置"
	},
	["PlacementSubMenu_Firework-List-ParticleName"] = {
		["en"] = "Particle Name",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Nome do Partícula",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "粒子名"
	},

	-- MultiplayerSubMenu
	["MultiplayerSubMenu-Subtitle"] = {
		["en"] = "Multiplayer",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Multijogador",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "多人创作"
	},
	["MultiplayerSubMenu-Button-No-Invitation"] = {
		["en"] = "You Have Not Received Any Invitation",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Você não recebeu nenhuma convite",
		["mx"] = "",
		["cn"] = "您尚未收到任何邀请"
	},
	["MultiplayerSubMenu-Button-Invite"] = {
		["en"] = "Invite Other Players",
		["br"] = "Convidar Outros Jogadores",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "邀请其他玩家"
	},
	["MultiplayerSubMenu-Button-Invite-Desc"] = {
		["en"] = "Please save the map first",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Por favor, salve o mapa primeiro",
		["mx"] = "",
		["cn"] = "请先保存地图"
	},

	-- MultiplayerSubMenu_Invite
	["MultiplayerSubMenu_Invite-Subtitle"] = {
		["en"] = "Available List",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Lista de Disponível",
		["mx"] = "",
		["cn"] = "可用列表"
	},
	["MultiplayerSubMenu_Invite-Button-No-Result"] = {
		["en"] = "No Players To Invite",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Nenhum Jogador Para Convidar",
		["mx"] = "",
		["cn"] = "没有可邀请的玩家"
	},

	-- WeatherSubMenu
	["WeatherSubMenu-Subtitle"] = {
		["en"] = "Weather Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Clima",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "天气设置"
	},
	["CLEAR"] = {
		["en"] = "Clear",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Limpo",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "晴朗"
	},
	["EXTRASUNNY"] = {
		["en"] = "Extrasunny",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Sol sem nuvens",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "晴天"
	},
	["CLOUDS"] = {
		["en"] = "Clouds",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Nuvens",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "多云"
	},
	["OVERCAST"] = {
		["en"] = "Overcast",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Nublado",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "阴天"
	},
	["RAIN"] = {
		["en"] = "Rain",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Chuva",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "下雨"
	},
	["CLEARING"] = {
		["en"] = "Clearing",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Limpeza",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "转晴"
	},
	["THUNDER"] = {
		["en"] = "Thunder",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Trovão",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "打雷"
	},
	["SMOG"] = {
		["en"] = "Smog",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Smog",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "雾霾"
	},
	["FOGGY"] = {
		["en"] = "Foggy",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Névoa",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "大雾"
	},
	["XMAS"] = {
		["en"] = "Christmas",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Natal",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "圣诞"
	},
	["SNOW"] = {
		["en"] = "Snow",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Neve",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "下雪"
	},
	["SNOWLIGHT"] = {
		["en"] = "Snowlight",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Luz de Neve",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "小雪"
	},
	["BLIZZARD"] = {
		["en"] = "Blizzard",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Nevasca",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "暴风雪"
	},
	["HALLOWEEN"] = {
		["en"] = "Halloween",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Halloween",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "万圣节"
	},
	["NEUTRAL"] = {
		["en"] = "Neutral",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Neutral",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "舒适"
	},

	-- TimeSubMenu
	["TimeSubMenu-Subtitle"] = {
		["en"] = "Time Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções de Horário",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "时间设置"
	},
	["Hours"] = {
		["en"] = "Hours",
		["br"] = "小时",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "小时"
	},
	["Minutes"] = {
		["en"] = "Minutes",
		["br"] = "分钟",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "分钟"
	},
	["Seconds"] = {
		["en"] = "Seconds",
		["br"] = "秒数",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "秒数"
	},
	["Lock"] = {
		["en"] = "Lock Time",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Travar Horário",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "锁定时间"
	},

	-- MiscSubMenu
	["MiscSubMenu-Subtitle"] = {
		["en"] = "Misc Options",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Opções Diversas",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "杂项设置"
	},
	["MiscSubMenu-List-CamMoveSpeed"] = {
		["en"] = "Cam Move Speed",
		["br"] = "相机移动速度",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "相机移动速度"
	},
	["MiscSubMenu-List-CamRotateSpeed"] = {
		["en"] = "Cam Rotate Speed",
		["br"] = "相机转动速度",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "相机转动速度"
	},
	["MiscSubMenu-CheckBox-DisableNpc"] = {
		["en"] = "Disable Npc And Traffic",
		["br"] = "禁用行人与交通",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "禁用行人与交通"
	},
	["MiscSubMenu-CheckBox-RadarBigmap"] = {
		["en"] = "Radar Bigmap",
		["br"] = "雷达大地图",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "雷达大地图"
	},

	-- Custom Msgs
	["title-limit"] = {
		["en"] = "Character limit: 20",
		["br"] = "字符数限制: 20",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "字符数限制: 20"
	},
	["title-exist"] = {
		["en"] = "Title already exists",
		["br"] = "标题已存在",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "标题已存在"
	},
	["title-error"] = {
		["en"] = "Invalid title",
		["br"] = "标题无效",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "标题无效"
	},
	["url-http-error"] = {
		["en"] = "Not https",
		["br"] = "不是https",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "不是https"
	},
	["url-error"] = {
		["en"] = "Invalid url",
		["br"] = "链接无效",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "链接无效"
	},
	["result-limit"] = {
		["en"] = "Exceeded the limit, only 50 results were returned",
		["br"] = "超出数量，只返回了50个结果",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "超出数量，只返回了50个结果"
	},
	["load-success"] = {
		["en"] = "Loaded",
		["br"] = "已加载",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "已加载"
	},
	["update-success"] = {
		["en"] = "Updated",
		["br"] = "已更新",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "已更新"
	},
	["save-success"] = {
		["en"] = "Saved",
		["br"] = "已保存",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "已保存"
	},
	["publish-success"] = {
		["en"] = "Published",
		["br"] = "已发布",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "已发布"
	},
	["export-success"] = {
		["en"] = "Exported a copy to Discord",
		["br"] = "已导出副本至Discord",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "已导出副本至Discord"
	},
	["export-failed"] = {
		["en"] = "Export copy failed (This is a server side error)",
		["br"] = "导出副本失败 (这是服务器端的错误)",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "导出副本失败 (这是服务器端的错误)"
	},
	["wrong-artifact"] = {
		["en"] = "Unable to save file, please contact the server owner to update or downgrade the server artifact",
		["br"] = "无法保存文件, 请联系服主更新或者降级服务器工件",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "无法保存文件, 请联系服主更新或者降级服务器工件"
	},
	["no-permission"] = {
		["en"] = "Permission denied",
		["br"] = "没有权限",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "没有权限"
	},
	["no-discord"] = {
		["en"] = "Discord not detected",
		["br"] = "未检测到discord",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "未检测到discord"
	},
	["ugc-wait"] = {
		["en"] = "Still waiting for results, number of queries: %s",
		["br"] = "仍在等待结果，已查询次数: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "仍在等待结果，已查询次数: %s"
	},
	["ugc-not-exist"] = {
		["en"] = "Failed to get a valid map",
		["br"] = "无法获取有效的地图",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "无法获取有效的地图"
	},
	["json-not-exist"] = {
		["en"] = "File does not exist",
		["br"] = "文件不存在",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "文件不存在"
	},
	["thumbnail-error"] = {
		["en"] = "Invalid thumbnail",
		["br"] = "缩略图无效",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "缩略图无效"
	},
	["vehicle-hash-null"] = {
		["en"] = "Vehicle: %s does not exist",
		["br"] = "载具: %s 不存在",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "载具: %s 不存在"
	},
	["respawn-tip"] = {
		["en"] = "Press %s to respawn",
		["br"] = "按下 %s 重生",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "按下 %s 重生"
	},
	["checkpoints-round-lock"] = {
		["en"] = "Special checkpoint must be circular",
		["br"] = "特殊检查点必须为圆形",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "特殊检查点必须为圆形"
	},
	["checkpoints_2-null"] = {
		["en"] = "Secondary checkpoint: %s does not exist",
		["br"] = "次要检查点: %s 不存在",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "次要检查点: %s 不存在"
	},
	["checkpoints_2-exist"] = {
		["en"] = "Secondary checkpoint: %s already exist",
		["br"] = "次要检查点: %s 已存在",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "次要检查点: %s 已存在"
	},
	["checkpoints_2-failed"] = {
		["en"] = "Inserting secondary checkpoint failed",
		["br"] = "插入次要检查点失败",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "插入次要检查点失败"
	},
	["checkpoints_2-planeRot-failed"] = {
		["en"] = "Secondary checkpoint cannot be set as plane rot checkpoint yet",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Secondary checkpoint cannot be set as plane rot checkpoint yet",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "次要检查点暂不支持设置为飞行方向检查点"
	},
	["object-hash-null"] = {
		["en"] = "Model: %s does not exist",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Model: %s does not exist",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "模型: %s 不存在"
	},
	["reset-transformVehicles"] = {
		["en"] = "Transform vehicles list reset",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Transform vehicles list reset",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "已重置幻变载具列表"
	},
	["z-limit"] = {
		["en"] = "Height limit: -199∼2699",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Height limit: -199∼2699",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "高度限制: -199∼2699"
	},
	["rot-limit"] = {
		["en"] = "Rotation limit: -9999∼9999",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "Rotation limit: -9999∼9999",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "旋转限制: -9999∼9999"
	},
	["error-input"] = {
		["en"] = "The input data is invalid",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["br"] = "The input data is invalid",
		["pl"] = "",
		["ru"] = "",
		["ko"] = "",
		["zh"] = "",
		["jp"] = "",
		["mx"] = "",
		["cn"] = "输入的数据无效"
	},
	["startingGrid-error1"] = {
		["en"] = "Please shorten the starting grid interval",
		["br"] = "Por favor, diminua o intervalo da grade de início",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "请缩短起跑位间隔"
	},
	["startingGrid-error2"] = {
		["en"] = "Cannot place starting grid here",
		["br"] = "Não é possível posicionar a grade de início aqui",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "无法在此处放置起跑位"
	},
	["checkpoint-error"] = {
		["en"] = "Cannot place checkpoint here",
		["br"] = "Não é possível posicionar o ponto de controle aqui",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "无法在此处放置检查点"
	},
	["object-error"] = {
		["en"] = "Cannot place object here",
		["br"] = "Não é possível posicionar o objeto aqui",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "无法在此处放置道具"
	},
	["visible-dynamic"] = {
		["en"] = "Dynamic props must be visible",
		["br"] = "Props dinâmicos devem ser visíveis",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "动态道具必须可见"
	},
	["add-hash"] = {
		["en"] = "Replaced model to: %s",
		["br"] = "Modelo substituído para: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "替换模型为: %s"
	},
	["wait-models"] = {
		["en"] = "Validating the list of available models: %s",
		["br"] = "Validando a lista de modelos disponíveis: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "正在验证可用模型列表: %s"
	},
	["wait-models-done"] = {
		["en"] = "Creator is ready for you",
		["br"] = "O criador está pronto para você",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "制作器已为你准备好"
	},
	["blimp-text-limit"] = {
		["en"] = "Character limit: 100",
		["br"] = "Limite de caracteres: 100",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "字符数限制: 100"
	},
	["join-session"] = {
		["en"] = "%s is joining the multiplayer session",
		["br"] = "%s está entrando na sessão multijogador",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 正在加入此多人会话"
	},
	["join-session-success"] = {
		["en"] = "Joined the multiplayer session",
		["br"] = "Entrou na sessão multijogador",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "已加入多人会话"
	},
	["join-session-failed"] = {
		["en"] = "Multiplayer session does not exist",
		["br"] = "Sessão multijogador não existe",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "该会话不存在"
	},
	["join-session-trying"] = {
		["en"] = "Current map is being edited, try joining a multiplayer session",
		["br"] = "O mapa atual está sendo editado, tente entrar em uma sessão multijogador",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "当前地图正在编辑中，尝试加入一个多人会话"
	},
	["left-session"] = {
		["en"] = "%s left the multiplayer session",
		["br"] = "%s saiu da sessão multijogador",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 已离开此多人会话"
	},
	["join-session-wait"] = {
		["en"] = "The network of %s is poor, please wait",
		["br"] = "A conexão de %s está ruim, por favor aguarde",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 的网络较差, 请等待"
	},
	["receive-invitation"] = {
		["en"] = "Received a multiplayer creation invitation from %s: %s",
		["br"] = "Recebeu um convite de criação multiplayer de %s: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "收到了来自 %s 的多人创作邀请: %s"
	},
	["session-data-rollback"] = {
		["en"] = "Data conflict, the latest data has been synchronized",
		["br"] = "Conflito de dados, os dados mais recentes foram sincronizados",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "数据冲突，已同步最新数据"
	},
	["published-status-publish"] = {
		["en"] = "%s published the map",
		["br"] = "%s publicou o mapa",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 发布了地图"
	},
	["published-status-update"] = {
		["en"] = "%s updated the map",
		["br"] = "%s atualizou o mapa",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 更新了地图"
	},
	["published-status-save"] = {
		["en"] = "%s saved the map",
		["br"] = "%s salvou o mapa",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 保存了地图"
	},
	["published-status-cancel"] = {
		["en"] = "%s unpublished the map",
		["br"] = "%s despublicou o mapa",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 取消发布了地图"
	},
	["title-sync"] = {
		["en"] = "%s updated title: %s",
		["br"] = "%s atualizou o título: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 更新了标题: %s"
	},
	["thumbnail-sync"] = {
		["en"] = "%s updated thumbnail",
		["br"] = "%s atualizou a miniatura",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 更新了缩略图"
	},
	["test-vehicle-sync"] = {
		["en"] = "%s updated default test vehicle: %s",
		["br"] = "%s atualizou o veículo de teste padrão: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 更新了默认测试载具: %s"
	},
	["blimp-text-sync"] = {
		["en"] = "%s updated blimp text: %s",
		["br"] = "%s atualizou o texto do dirigível: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 更新了飞艇文本: %s"
	},
	["transformVehicles-sync"] = {
		["en"] = "%s updated transform vehicles list",
		["br"] = "%s atualizou a lista de veículos transformados",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s 更新了幻变载具列表"
	},
	["startingGrid-insert"] = {
		["en"] = "%s inserted starting grid: %s",
		["br"] = "%s inseriu grade de início: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s inseriu grade de início: %s"
	},
	["startingGrid-delete"] = {
		["en"] = "%s deleted starting grid: %s",
		["br"] = "%s excluiu grade de início: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s excluiu grade de início: %s"
	},
	["checkpoints-insert-primary"] = {
		["en"] = "%s inserted primary checkpoint: %s",
		["br"] = "%s inseriu ponto de controle primário: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s inseriu ponto de controle primário: %s"
	},
	["checkpoints-insert-secondary"] = {
		["en"] = "%s inserted secondary checkpoint: %s",
		["br"] = "%s inseriu ponto de controle secundário: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s inseriu ponto de controle secundário: %s"
	},
	["checkpoints-delete-primary"] = {
		["en"] = "%s deleted primary checkpoint: %s",
		["br"] = "%s excluiu ponto de controle primário: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s excluiu ponto de controle primário: %s"
	},
	["checkpoints-delete-secondary"] = {
		["en"] = "%s deleted secondary checkpoint: %s",
		["br"] = "%s excluiu ponto de controle secundário: %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s excluiu ponto de controle secundário: %s"
	},
	["fixtures-sync"] = {
		["en"] = "%s updated fixtures list",
		["br"] = "%s atualizou a lista de fixações",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s atualizou a lista de fixações"
	},
	["firework-sync"] = {
		["en"] = "%s updated firework settings",
		["br"] = "%s atualizou as configurações de fogos de artifício",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s atualizou as configurações de fogos de artifício"
	},
	["objects-place"] = {
		["en"] = "%s placed new object: hash = %s, x = %s, y = %s, z = %s",
		["br"] = "%s posicionou novo objeto: hash = %s, x = %s, y = %s, z = %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s posicionou novo objeto: hash = %s, x = %s, y = %s, z = %s"
	},
	["objects-delete"] = {
		["en"] = "%s deleted object: %s, hash = %s, x = %s, y = %s, z = %s",
		["br"] = "%s excluiu o objeto: %s, hash = %s, x = %s, y = %s, z = %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s excluiu o objeto: %s, hash = %s, x = %s, y = %s, z = %s"
	},
	["template-place"] = {
		["en"] = "%s placed %s objects",
		["br"] = "%s posicionou %s objetos",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s posicionou %s objetos"
	},
	["move-all"] = {
		["en"] = "%s moved all, offset: x = %s, y = %s, z = %s",
		["br"] = "%s moveu tudo, deslocamento: x = %s, y = %s, z = %s",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "%s moveu tudo, deslocamento: x = %s, y = %s, z = %s"
	},

	-- Buttons
	["SelectStartingGrid"] = {
		["en"] = "Select Starting Grid",
		["br"] = "Selecionar Grade de Início",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "选择起跑位"
	},
	["UpdateStartingGrid"] = {
		["en"] = "Update Starting Grid",
		["br"] = "Atualizar Grade de Início",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "更新起跑位"
	},
	["SelectObject"] = {
		["en"] = "Select Object",
		["br"] = "Selecionar Objeto",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "选择道具"
	},
	["DeselectObject"] = {
		["en"] = "Deselect Object",
		["br"] = "Desmarcar Objeto",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "取消选择道具"
	},
	["PreviewHeight"] = {
		["en"] = "Preview Height",
		["br"] = "Pré-visualizar Altura",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "预览高度"
	},
	["DeselectCheckpoint"] = {
		["en"] = "Deselect Checkpoint",
		["br"] = "Desmarcar Ponto de Controle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "取消选择检查点"
	},
	["Go"] = {
		["en"] = "Go",
		["br"] = "Ir",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "确定"
	},
	["Back"] = {
		["en"] = "Back",
		["br"] = "Voltar",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "返回"
	},

	-- Tips
	["quit-test"] = {
		["en"] = "Press ~INPUT_HUD_SPECIAL~ to quit test",
		["br"] = "Pressione ~INPUT_HUD_SPECIAL~ para sair do teste",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "按下 ~INPUT_HUD_SPECIAL~ 退出测试"
	},
	["paste-url"] = {
		["en"] = "Paste the image or json url",
		["br"] = "Cole a URL da imagem ou do json",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "粘贴图片或者json链接"
	},

	-- Blips
	["blip-object"] = {
		["en"] = "Props",
		["br"] = "Props",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "道具"
	},
	["blip-checkpoint"] = {
		["en"] = "Checkpoints",
		["br"] = "Pontos de Controle",
		["fr"] = "",
		["de"] = "",
		["it"] = "",
		["es"] = "",
		["mx"] = "",
		["cn"] = "检查点"
	}
}

GetTranslate = function(text, currentLanguage)
	local currentLanguage = currentLanguage or (global_var and global_var.currentLanguage) or 0
	if text and translation[text] then
		if translation[text][languageCode[currentLanguage]] and translation[text][languageCode[currentLanguage]] ~= "" then
			return translation[text][languageCode[currentLanguage]]
		else
			return translation[text]["en"]
		end
	end
	return "Error Text"
end
